### ISSUE TITLE
HP - immagini

### ISSUE THREAD

**Issue by nicoladl** [nicoladl/Mondialfrutta#1]
- [x] header video - shutterstock
- [x] azienda verticale - istock
- [x] azienda orizzontale - istock
- [x] servizi verticale - istock
- [x] servizi orizzontale - istock
- [x] clienti verticale - istock
- [x] clienti orizzontale - istock
- [x] stagionalità verticale - shutterstock
- [x] stagionalità orizzontale - shutterstock

**Comment by nicoladl** [comment]
la parte di stagionalità è da post-produrre

**Comment by pverduga** [comment]
![istock-176895852](https://user-images.githubusercontent.com/3356106/34568093-ff583358-f164-11e7-83e7-332c595c570f.jpg)
![istock-182174646](https://user-images.githubusercontent.com/3356106/34568094-ff859fdc-f164-11e7-8e9d-dd1776a4f6bd.jpg)
![istock-485053182](https://user-images.githubusercontent.com/3356106/34568095-ffb3969e-f164-11e7-87dc-204677824156.jpg)
![Uploading iStock-506788598.jpg…]()

**Comment by pverduga** [comment]
https://we.tl/1tWuUd8c3g
