### ISSUE TITLE
AZIENDA - immagini

### ISSUE THREAD

**Issue by nicoladl** [nicoladl/Mondialfrutta#18]
- [x] header - shutterstock
- [x] video - shutterstock
- [x] conor veneto - cliente
- [x] HDF - cliente

**Comment by pverduga** [comment]
[CONOR VENETO Quadricromia esecutivo.pdf](https://github.com/nicoladl/Mondialfrutta/files/1631396/CONOR.VENETO.Quadricromia.esecutivo.pdf)
[logo HFD.pdf](https://github.com/nicoladl/Mondialfrutta/files/1631397/logo.HFD.pdf)

**Comment by pverduga** [comment]
@nicoladl  : servirebbe ridurre la grandezza del logo hfd

Grazie

**Comment by nicoladl** [comment]
fatto 
:*
