### ISSUE TITLE
mobile: visualizzazione mappa rete logistica 

### ISSUE THREAD

**Issue by pverduga** [nicoladl/Mondialfrutta#25]
puoi vedere se c'è qualche impostazione apposta per la visualizzazione mobile? 😽

**Comment by nicoladl** [comment]
![photo_2018-01-04_22-22-09](https://user-images.githubusercontent.com/2022727/34639558-2e3f74fa-f2e2-11e7-98c0-409abb9f5b2d.jpg)

**Comment by pverduga** [comment]
è stata spostata a sx e va meglio... ma non risulta ancora non centrata l'italia.  Si riesce a migliorare?
![photo_2018-01-15_12-28-34](https://user-images.githubusercontent.com/3356106/34940392-a8c5215c-f9ef-11e7-9199-3e9cf41f13f4.jpg)

**Comment by pverduga** [comment]
![photo_2018-01-15_12-28-34](https://user-images.githubusercontent.com/3356106/34962896-0c716bb0-fa46-11e7-92a6-a45b71f2404b.jpg)

**Comment by nicoladl** [comment]
iphone8
