### ISSUE TITLE
RETE LOGISTICA: aggiungere porti e nodi

### ISSUE THREAD

**Issue by pverduga** [nicoladl/Mondialfrutta#35]
**Nodi:**

Avezzano
Ancona

**Porti:**

Trieste
Civitavecchia
Salerno
Bari
Koper
Ancona

**Comment by pverduga** [comment]
@nicoladl  servirebbe eliminare i porti ripetuti nell'elenco dei nodi logistici:

Ancona
Catania
Genova
Livorno
Nizza
Napoli
Piombino
Ravenna
Savona
Venezia

**Comment by nicoladl** [comment]
Quindi adesso abbiamo capito che non tutti i porti sono anche Nodi Logistici, anche se ci avevano detto il contrario. 
:bomb:
