### ISSUE TITLE
Stagionalità: verificare crop/resize delle immagini prodotto 

### ISSUE THREAD

**Issue by pverduga** [nicoladl/Mondialfrutta#6]

**Comment by nicoladl** [comment]
Il problema è che l'immagine non era quadrata.
Cerchiamo di sceglierle quadrate poi il resize le ridimensionerà, se nel caso rettangolari accertarsi che il soggetto sia nell'area quadrata dell'immagine altrimenti il crop taglierà il contenuto.

Il pomodoro l'ho sistemato io.
